### ISSUE TITLE
docker-compose: Unable to enable IP forwarding!

### ISSUE THREAD

**Issue by konsumer** [jakev/mitm-helper-vpn#4]
I'm hoping to make a single docker-compose I can run that is a VPN and forces traffic through it for capture (via mitm-proxy and eventually also tcpdump/wireshark)

I've got this docker-compose:

```yml
version: "3.3"

services:
  mitm:
    image: mitmproxy/mitmproxy
    command: mitmweb --web-host 0.0.0.0 --showhost
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./config:/home/mitmproxy/.mitmproxy
    networks:
      - capture-net

  vpn:
    build: ./
    networks:
      - capture-net
    volumes:
      - ./config/mitm-pptp.conf:/etc/mitm-pptp.conf

networks:
  capture-net:
    driver: bridge
```

My `Dockerfile` for this project is this:

```Dockerfile
FROM debian:buster

RUN apt-get -qqy update && apt-get install -qqy pptpd ppp python wget
RUN wget https://github.com/jakev/mitm-helper-vpn/raw/master/build/mitm-helper-vpn_0.1.deb && apt-get install -y ./mitm-helper-vpn_0.1.deb && rm mitm-helper-vpn_0.1.deb
RUN apt-get remove --purge -y wget && rm -rf /var/lib/apt/lists/*

CMD ["mitm-pptp", "-v"]
```

My `mitm-pptp.conf` looks like this:

```ini
[HTTP Proxies]
ProxyPort:8080
ForwardPorts:80,443
```

When I run it, I get this error-log:

```
Starting vpn_mitm_1  ... done
Recreating vpn_vpn_1 ... done
Attaching to vpn_mitm_1, vpn_vpn_1
vpn_1   | [Error] Unable to enable IP forwarding!
vpn_1   | [Error] Unable to flush iptables!
vpn_1   | [Error] Unable to configure iptables!
vpn_1   | [Error] Unable to disable IP forwarding!
mitm_1  | Web server listening at http://0.0.0.0:8081/
mitm_1  | No web browser found. Please open a browser and point it to http://0.0.0.0:8081/
mitm_1  | Proxy server listening at http://*:8080
```

What else do I need to do?
